/* eslint-disable @typescript-eslint/no-namespace */
/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace user_proto {
  export interface UserService {
    // API for user login
    login(
      data: LoginRequest,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<LoginResponse>;
  }
  export interface LoginRequest {
    // Type of login (e.g., email, username)
    type?: string;
    // Login identifier (e.g., email address or username)
    identity?: string;
  }
  export interface LoginResponse {
    // User details
    user?: LoginResponse.User;
    // Authentication token for the session
    token?: string;
  }
  export namespace LoginResponse {
    export interface User {
      // Name of the user
      name?: string;
      // Email address of the user
      email?: string;
      // Phone number of the user
      phoneNumber?: string;
    }
  }
}
