/* eslint-disable @typescript-eslint/no-namespace */
/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace user_proto {
  export interface UserService {
    // API for user login
    login(
      data: LoginRequest,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<LoginResponse>;
    validateUser(
      data: ValidateUserRequest,
      metadata?: Metadata,
      ...rest: any[]
    ): Observable<ValidateUserResponse>;
  }
  export interface LoginRequest {
    // Type of login (e.g., email, username)
    type?: string;
    // Login identifier (e.g., email address or phone number)
    identity?: string;
    // Password of the user
    password?: string;
  }
  export interface User {
    // Name of the user
    name?: string;
    // Email address of the user
    email?: string;
    // Phone number of the user
    phoneNumber?: string;
    id?: number;
  }
  export interface ValidateUserResponse {
    // Header for the response
    responseHeader?: common_proto.MessageResponseHeader;
    // User details
    user?: user_proto.User;
  }
  export interface ValidateUserRequest {
    token?: string;
  }
  export interface LoginResponse {
    // Header for the response
    responseHeader?: common_proto.MessageResponseHeader;
    // User details
    user?: user_proto.User;
    token?: string;
  }
}
export namespace common_proto {
  export interface MessageResponseHeader {
    // Status code of the response
    code?: number;
    // Response message (e.g., error or success message)
    message?: string;
    // Whether the request was successful
    success?: boolean;
  }
}
